builds:
  - main: main.go
    binary: "terraform-provider-exoscale_{{.Tag}}_x{{.Commit}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

sign:
  cmd: gpg
  args: ["-u", "ops@exoscale.ch", "--detach-sign", "${artifact}"]
  artifacts: all


dist: build

git:
  short_hash: true
