language: go

dist: trusty

go:
- "1.9"
- "1.10"
- tip

env:
  - MY_GOOS=linux MY_GOARCH=amd64
  - MY_GOOS=darwin MY_GOARCH=amd64
  - MY_GOOS=windows MY_GOARCH=amd64

install:
  - make deps
  - export GOOS=$(MY_GOOS)
  - export GOARCH=$(MY_GOARCH)

script:
  - make build
