dist: trusty
sudo: required
services:
- docker
language: go
go:
- "1.11.x"
- "1.12.x"
- tip

env:
  - GO111MODULE=off

git:
  depth: 1

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- make tools

script:
- make lint
- test "${TRAVIS_PULL_REQUEST}" != "false" && make test || echo "skipping test"
- test "${TRAVIS_PULL_REQUEST}" = "false" && make testacc || echo "skipping testacc"
  # it fails on TravisCI
# - GO111MODULE=on make vendor-status
# it requires changes in hashicorp/terraform-website
# - make website-lint
# - make website-test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

jobs:
  include:
  - stage: gh-pages
    go: "1.11.x"
    if: branch = master AND type = push
    script: |
      gem install bundler
      cd website
      bundle install
      bundle exec middleman build
      cd build
      git init
      git config user.name "TravisCI"
      git config user.email "travis@travis-ci.org"
      git add .
      git commit -m "Deployed to GitHub pages"
      git push -f -q "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" master:gh-pages
