[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.12.2"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.10"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.39.0"

[prune]
  go-tests = true
  unused-packages = true
