[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.9.17"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  #version = "0.11.6"
  branch = "master"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.33.0"

[prune]
  go-tests = true
  unused-packages = true
