[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.9.15"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  #version = "0.11.6"
  branch = "master"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.33.0"
