[[constraint]]
  name = "github.com/exoscale/egoscale"
  #version = "0.10.2"
  branch = "fix-activate-ip6"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.37.0"

[prune]
  go-tests = true
  unused-packages = true
