[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.9.11"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.3"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.32.0"
